version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  sonar-python:
    enabled: true
    config:
      minimum_severity: major
