version: 2
jobs:
  build:
    docker:
      - image: python:3.6
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
          paths:
            - ~/cache/pip

      - run:
          name: Install dependencies
          command: pip install --cache-dir ~/cache/pip -r requirements.txt

      - save_cache:
          name: Save pip cache
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/cache/pip

      - run:
          name: Run tests
          command: |
            set -xu
            ./tests.sh
