version: 2
jobs:
  build:
    docker:
      - image: python:3.6
        environment:
          PRE_COMMIT_HOME: /root/cache/pre-commit
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /root/cache/pip
            - /root/cache/pre-commit
      - run:
          name: Install dependencies
          command: |
            pip install --cache-dir /root/cache/pip -r requirements.txt
            pip install --cache-dir /root/cache/pip pre-commit==1.8.2
            pre-commit install --install-hooks
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /root/cache/pip
            - /root/cache/pre-commit
      - run:
          name: Run linting
          command: pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            set -xu
            ./tests.sh
